### PR TITLE
add route with 2 parameters

### PR DESCRIPTION
**Pull request by vadim9999**

### CODE REVIEW

**Comment by vadim9999** [comment]
But it's a problem when you will type Fresh vegetables in URL browser will instead of space insert Fresh%20Vegetables

**Comment by atherdon** [comment]
try to clean it up with this module: https://www.npmjs.com/package/striptags
if it don't help, i'll find something else. will google about lodash

**Comment by atherdon** [comment]
also you can try lodash.escape

**Comment by atherdon** [comment]
actually it called string sanitization

**Comment by atherdon** [comment]
also you can try https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Comment by vadim9999** [comment]
req.params.department returns words without special symbols
for example 
Fresh%20Vegetables
req.params.department return Fresh Vegetables. The problem is that whe I type in a field of URL it's automatic make first letter of words big. when I will type like this /fresh%20vegetables/ it will return fresh vegetables
I think If someone want to use it just need instead of space use %20 and it will be ok

**Comment by atherdon** [comment]
i think about another way - we can change it from text at urls to ids amd everything will be much simple, less long and will work fine

**Pull request merged**
